name: release

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture'
        default: 'amd64'
        required: true
      version:
        description: 'Version'
        default: 'v2021.02.3-?'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install github-release
      run: |
        sudo wget https://github.com/github-release/github-release/releases/download/v0.9.0/linux-amd64-github-release.bz2 -O /usr/local/bin/github-release.bz2
        sudo bunzip2 /usr/local/bin/github-release.bz2
        sudo chmod 0755 /usr/local/bin/github-release

    - name: Build
      run: |
        ARCH=${{ github.event.inputs.arch }} RELEASE_VERSION=${{ github.event.inputs.version }} make release

    - name: Publish release
      run: ${PWD}/dist/publish.sh
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
